In [2]:
import pandas as pd
df = pd.DataFrame({
    "City": ["Bengaluru", "Mysuru", "Bengaluru", "Mysuru",
             "Bengaluru", "Mysuru", "Bengaluru", "Mysuru"],
    "Category": ["Electronics", "Electronics", "Clothing", "Clothing",
                 "Electronics", "Clothing", "Clothing", "Electronics"],
    "Sales": [50000, 30000, 15000, 20000, 45000, 25000, 18000, 35000],
    "Profit": [8000, 4000, 3000, 5000, 7000, 6000, 3500, 4500]
})
pd.pivot_table(df,index="City",columns="Category",values="Sales", aggfunc="sum")

Category   Clothing  Electronics
City
Bengaluru     33000        95000
Mysuru        45000        65000

In [3]:
pd.pivot_table(df,index="City",columns="Category",values="Profit", aggfunc="mean")

Category   Clothing  Electronics
City
Bengaluru    3250.0       7500.0
Mysuru       5500.0       4250.0

In [4]:
result = pd.pivot_table(
    df,
    index="City",
    columns="Category",
    values=["Sales", "Profit"],
    aggfunc={"Sales": "sum", "Profit": "mean"}
)
print(result)

            Profit                Sales
Category  Clothing Electronics Clothing Electronics
City
Bengaluru   3250.0      7500.0    33000       95000
Mysuru      5500.0      4250.0    45000       65000